#config/meta.yml

meta_product_name: "ShelfUp"
meta_title: "ShelfUp - Rent Yourself a Shelf"
meta_description: "Market your brand in a new way with ShelfUp!
ShelfUp let's you display your products in physical stores and reach your customers where it really matters."
meta_image: "metashelfup.jpg"
